server:
  port: 8301
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8001/eureka/ #配置注册中心地址

spring:
  application:
    name: service-zuul
# 以/api-ribbon/ 开头的请求都转发给service-ribbon服务；
# 以/api-feign/开头的请求都转发给service-feign服务；
zuul:
  routes:
    api-ribbon:
      path: /api-ribbon/**
      serviceId: service-ribbon
    api-feign:
      path: /api-feign/**
      serviceId: service-feign

