server:
  port: 8201
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8001/eureka/   #配置注册中心地址
# 指定服务注册的宿主ip
# eureka.instance.ip-address=192.168.1.1
# 配置注册时使用ip而不是主机名
#eureka.instance.prefer-ip-address=true

spring:
  application:
    name: service-ribbon